#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
GLOSSARY="$ROOT/glossary.json"
MACROS="$ROOT/styles/macros.html"
QMD="$ROOT/glossary.qmd"
GLOSSARY_LUA="$ROOT/glossary.lua"

# --- styles/macros.html ---
{
  echo "<script>"
  echo "MathJax = { tex: { macros: {"
  jq -r 'to_entries[]
    | select(.value | type == "object")
    | select(.value.macro != null and .value.macro != "")
    | "  \(.value.macro): \"\(.value.latex)\","' "$GLOSSARY" | sed 's/\\/\\\\/g'
  echo "}}};"
  echo "</script>"
} > "$MACROS"

# --- notes/glossary.qmd ---
{
  echo "| Term | Definition |"
  echo "|------|------------|"
  jq -r 'to_entries[]
    | select(.value | type == "object")
    | "| <abbr title=\"\(.value.def)\">\(.key)</abbr> | \(.value.def) |"' "$GLOSSARY"
} > "$QMD"

# --- glossary.lua (Pandoc filter for [term]{.gloss} spans) ---
{
  cat << 'EOF'
-- AUTO-GENERATED by sync_glossary.sh — do not edit by hand.
-- Edit glossary.json instead, then re-run sync_glossary.sh.
--
-- Usage in .qmd:           [surface of section]{.gloss}
-- Explicit key, if display text differs from the glossary entry:
--           [SoS]{.gloss key="surface of section"}
--
-- Renders as a hover/focus CSS popover (not a native `title` tooltip),
-- so $...$ math inside definitions gets picked up and rendered by
-- MathJax client-side, same as any other text on the page.
-- Styling lives in styles/custom.scss under .gloss-term / .gloss-tooltip.

local terms = {
EOF
  jq -r 'to_entries[]
    | select(.value | type == "object")
    | select(.value.def != null and .value.def != "")
    | "  [" + (.key | ascii_downcase | @json) + "] = " + (.value.def | @json) + ","' "$GLOSSARY"
  cat << 'EOF'
}

local function escape_html(s)
  s = s:gsub("&", "&amp;")
  s = s:gsub("<", "&lt;")
  s = s:gsub(">", "&gt;")
  return s
end

function Span(el)
  if not el.classes:includes("gloss") then return nil end

  local text = pandoc.utils.stringify(el)
  local key = el.attributes["key"] or text
  local def = terms[key:lower()]

  if not def then
    io.stderr:write("glossary.lua: no entry for '" .. key .. "'\n")
    return el -- leave untouched rather than failing the build
  end

  local html = '<span class="gloss-term" tabindex="0">'
    .. escape_html(text)
    .. '<span class="gloss-tooltip">' .. escape_html(def) .. '</span>'
    .. '</span>'

  return pandoc.RawInline("html", html)
end
EOF
} > "$GLOSSARY_LUA"

echo "sync_glossary: macros.html, glossary.qmd, and glossary.lua updated"