project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "topics/**/*.qmd"
  resources:
    - "pic/**"
    - "figures/**"

website:
  title: "Chaos"
  page-footer:
    center: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - darkly
      - styles/custom.scss
    toc: true
    toc-depth: 3
    code-fold: true
    link-external-newwindow: true
    include-after-body: styles/tasks.html
    include-in-header: styles/macros.html
    bibliography: lit/references.bib
