project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "topics/**/*.qmd"
    - "!glossary.qmd"
  resources:
    - "pic/**"
    - "figures/**"
    - "topics/**/*.html"

website:
  title: "Chaos"
  # page-footer:
  #   center: "Built with [Quarto](https://quarto.org)"
  sidebar:
    contents:
      - index.qmd
      - topics/day-logs/index.qmd
      - section: "Topics"
        contents:
          - topics/Theory/index.qmd
          - topics/henon-heiles/index.qmd
          - topics/self-organized-criticallity/index.qmd
      - section: "Logs"
        contents:
          - topics/26-08-03-log/index.qmd
          - topics/26-07-14-log/index.qmd
          - topics/26-07-08-log/index.qmd
          - topics/26-07-07-log/index.qmd
          - topics/26-06-20-log/index.qmd
          - topics/26-06-19-log/index.qmd
          - topics/26-06-17-log/index.qmd
          - topics/26-06-15-log/index.qmd
          - topics/26-06-14-log/index.qmd
          - topics/26-06-12-log/index.qmd
          - topics/26-06-11-log/index.qmd
          - topics/26-06-09-log/index.qmd
          - topics/26-06-05-log/index.qmd
          - topics/26-05-26-log/index.qmd
          - topics/26-05-27-log/index.qmd
          - topics/26-05-28-log/index.qmd



format:
  html:
    theme:
      - darkly
      - styles/custom.scss
    toc: true
    toc-depth: 3
    code-fold: true
    link-external-newwindow: true
    include-after-body:
      - styles/tasks.html
      # - styles/glossary.html
    include-in-header: styles/macros.html
    bibliography: literature/references.bib

filters:
  - glossary.lua
